[project]
name = "python-django"
version = "0.1.0"
description = "Django banking system with Cloudinary, Admin Soft Dashboard, and REST API support"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    # Core Django + server
    "django>=5.1.6",
    "gunicorn>=23.0.0",
    "whitenoise>=6.9.0",
    "dj-database-url>=2.3.0",
    # Database clients
    "mysqlclient==2.2.7",
    "psycopg[binary]>=3.2",
    # Cloudinary + storage
    "cloudinary==1.41.0",
    "django-cloudinary-storage==0.3.0",
    "django-storages>=1.14.4",
    # REST framework and extras
    "djangorestframework>=3.15.2",
    "django-cors-headers>=4.4.0",
    "django-admin-soft-dashboard==1.0.12",
    # Utility and PDF/report generation
    "xhtml2pdf==0.2.16",
    "reportlab>=4.1.0",
    "svglib==1.5.1",
    "tinycss2==1.3.0",
    "html5lib==1.1",
    "qrcode==7.4.2",
    "pypdf==5.0.0",
    "pyhanko==0.25.0",
    "pyhanko-certvalidator==0.26.3",
    # Misc tools
    "geocoder==1.38.1",
    "requests>=2.32.3",
    "packaging>=24.2",
    "future==1.0.0",
    "tzlocal==5.2",
    "pytz==2024.2",
    "user-agents>=2.2.0",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "black",
]

# Optional Wasmer-specific section
[tool.wasmer]
# The entry point for your Django app
entrypoint = "gunicorn mysite.wsgi:application --bind 0.0.0.0:${PORT:-8000}"

# Environment configuration
[tool.wasmer.env]
DJANGO_SETTINGS_MODULE = "mysite.settings"
PYTHONUNBUFFERED = "1"
