[package]
entrypoint = "start"

[dependencies]
"python/python" = ">=3.11"
"wasmer/bash" = "=1.0.24"

[fs]
"/app" = "."
"/opt/venv" = "/opt/venv"

[[command]]
name = "start"
module = "python/python:python"
runner = "wasi"

[command.annotations.wasi]
cwd = "/app"
main-args = [
    "-m",
    "uvicorn",
    "mysite.wsgi:application",
    "--interface=wsgi",
    "--host",
    "0.0.0.0",
    "--port",
    "8080",
]
env = [
    "PYTHONEXECUTABLE=/bin/python",
    "PYTHONHOME=/cpython",
    "PYTHONPATH=/app:/opt/venv/lib/python3.12/site-packages",
    "HOME=/app",
]

[[command]]
name = "after_deploy"
module = "python/python:python"
runner = "wasi"

[command.annotations.wasi]
cwd = "/app"
main-args = [
    "manage.py",
    "migrate",
]
env = [
    "PYTHONEXECUTABLE=/bin/python",
    "PYTHONHOME=/cpython",
    "PYTHONPATH=/app:/opt/venv/lib/python3.12/site-packages",
    "HOME=/app",
]
